// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmO4XbKqp6F39OOloDU7eeUYx8q1ntmK',
    appId: '1:325661304946:android:067cb9ddc21b610a80faeb',
    messagingSenderId: '325661304946',
    projectId: 'internalassessmentapp-d0e2d',
    storageBucket: 'internalassessmentapp-d0e2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpik4-FQrNCotJyhidJmQhQdWYiy8USH',
    appId: '1:325661304946:ios:e86d2dc5e362c8fc80faeb',
    messagingSenderId: '325661304946',
    projectId: 'internalassessmentapp-d0e2d',
    storageBucket: 'internalassessmentapp-d0e2d.firebasestorage.app',
    androidClientId: '325661304946-65d4a8684u4kmugq4m2jvgin2qgdrpta.apps.googleusercontent.com',
    iosClientId: '325661304946-ib18kli9ij54jqlvuok87nbk7fcde8q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.internalAssessmentApp',
  );

}